weights: weights/yolov5m.pt
cfg: models/yolov5m.yaml
data: data/GapTrain.yaml
hyp: data/hyps/hyp.scratch.yaml
epochs: 80
batch_size: 20
img_size:
- 160
- 160
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: null
bucket: ''
cache_images: false
image_weights: false
device: ''
multi_scale: false
single_cls: true
adam: false
sync_bn: false
workers: 8
project: runs/train
entity: null
name: yolov5m
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
local_rank: -1
save_dir: runs/train/yolov5m
